import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Loader2, AlertCircle } from "lucide-react";
import { useToast } from "@/components/ui/use-toast";

interface RouteLocation {
  stored_route_location_ID: number;
  route_location_name: string;
}

interface RouteResponse {
  no_routes_found?: boolean;
  no_matching_routes_found?: boolean;
  no_routes_message?: string;
  tabs?: string;
  tabContents?: string;
}

interface RouteDetailsRow {
  day: number;
  date: string;
  source: string;
  next: string;
  via: string;
  directVisit: boolean;
}

interface RouteDefaultSuggestionsModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSelectRoute: (routeDetails: RouteDetailsRow[], tabIndex: number) => void;
  noOfDays: number;
  arrivalLocation: string;
  departureLocation: string;
  startDate: string; // d-m-Y format
  endDate: string; // d-m-Y format
}

export const RouteDefaultSuggestionsModal = ({
  isOpen,
  onClose,
  onSelectRoute,
  noOfDays,
  arrivalLocation,
  departureLocation,
  startDate,
  endDate,
}: RouteDefaultSuggestionsModalProps) => {
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const [response, setResponse] = useState<RouteResponse | null>(null);
  const [selectedTabIndex, setSelectedTabIndex] = useState(0);
  const [routesData, setRoutesData] = useState<RouteDetailsRow[][]>([]);

  useEffect(() => {
    if (isOpen && arrivalLocation && departureLocation && noOfDays > 0) {
      fetchRoutes();
    }
  }, [isOpen, arrivalLocation, departureLocation, noOfDays, startDate, endDate]);

  const fetchRoutes = async () => {
    setLoading(true);
    try {
      const apiUrl = `${import.meta.env.VITE_API_URL || "http://localhost:4006"}/api/v1/itineraries/default-route-suggestions`;

      const response = await fetch(apiUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          _no_of_route_days: noOfDays,
          _arrival_location: arrivalLocation,
          _departure_location: departureLocation,
          _formattedStartDate: startDate,
          _formattedEndDate: endDate,
        }),
      });

      const data = (await response.json()) as RouteResponse;
      setResponse(data);

      if (data.no_routes_found) {
        toast({
          title: "No Routes Found",
          description:
            data.no_routes_message || "No default routes available for this selection.",
          variant: "destructive",
        });
      } else if (data.no_matching_routes_found) {
        toast({
          title: "No Matching Routes",
          description: "No routes match your criteria.",
          variant: "destructive",
        });
      } else if (data.tabs && data.tabContents) {
        // Parse the HTML response and extract route data
        parseRoutesFromResponse(data);
      }
    } catch (error) {
      console.error("Error fetching routes:", error);
      toast({
        title: "Error",
        description: "Failed to fetch route suggestions. Please try again.",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const parseRoutesFromResponse = (data: RouteResponse) => {
    // This is a simplified parser. In production, you might want to use a more robust HTML parser
    // For now, we'll parse the structure based on the pattern generated by the backend

    try {
      // Count the number of routes by counting route tabs
      const tabMatches = data.tabs?.match(/Route \d+/g) || [];
      const numRoutes = tabMatches.length;

      const parsedRoutes: RouteDetailsRow[][] = [];

      for (let i = 0; i < numRoutes; i++) {
        const tabIndex = i + 1;
        const routeDetails: RouteDetailsRow[] = [];

        // Extract rows for this specific route from tabContents
        const tableId = `custom_route_details_LIST_${tabIndex}`;
        const tableStartIdx = data.tabContents?.indexOf(`id="${tableId}"`) || -1;

        if (tableStartIdx > -1) {
          const tableEndIdx = data.tabContents?.indexOf(
            "</table>",
            tableStartIdx
          ) || -1;

          if (tableEndIdx > tableStartIdx) {
            const tableHtml = data.tabContents?.substring(
              tableStartIdx,
              tableEndIdx
            );

            // Parse rows from the table
            const rowMatches = tableHtml?.match(
              /<tr[^>]*>[\s\S]*?<\/tr>/g
            ) || [];

            // Skip the header row (first tr in tbody)
            for (let j = 1; j < rowMatches.length; j++) {
              const rowHtml = rowMatches[j];
              const dayMatch = rowHtml.match(/DAY (\d+)/);
              const dateMatch = rowHtml.match(
                /id="route_date_\d+_\d+"[^>]*>([^<]+)</
              );
              const sourceMatch = rowHtml.match(/name="source_location_\d+\[\]"[^>]*value="([^"]*)"/);
              const nextMatch = rowHtml.match(/name="next_visiting_location_\d+\[\]"[^>]*>[\s\S]*?<option[^>]*>([^<]+)<\/option>/);

              const day = dayMatch ? parseInt(dayMatch[1]) : 0;
              const date = dateMatch ? dateMatch[1] : "";
              const source = sourceMatch ? sourceMatch[1] : "";
              const next = nextMatch ? nextMatch[1] : "";

              if (day > 0) {
                routeDetails.push({
                  day,
                  date,
                  source,
                  next,
                  via: "",
                  directVisit: false,
                });
              }
            }
          }
        }

        if (routeDetails.length > 0) {
          parsedRoutes.push(routeDetails);
        }
      }

      setRoutesData(parsedRoutes);
    } catch (error) {
      console.error("Error parsing routes:", error);
      toast({
        title: "Error",
        description: "Failed to parse route data.",
        variant: "destructive",
      });
    }
  };

  const handleSelectRoute = () => {
    if (routesData.length > selectedTabIndex) {
      const selectedRoute = routesData[selectedTabIndex];
      onSelectRoute(selectedRoute, selectedTabIndex + 1);
      onClose();
    }
  };

  if (!isOpen) return null;

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-6xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Default Route Suggestions</DialogTitle>
        </DialogHeader>

        {loading ? (
          <div className="flex items-center justify-center py-12">
            <Loader2 className="h-8 w-8 animate-spin" />
            <span className="ml-2">Loading route suggestions...</span>
          </div>
        ) : response?.no_routes_found ? (
          <div className="flex items-start space-x-3 py-6 px-4 bg-orange-50 border border-orange-200 rounded-lg">
            <AlertCircle className="h-5 w-5 text-orange-600 flex-shrink-0 mt-0.5" />
            <div>
              <h3 className="font-semibold text-orange-900">
                {response.no_routes_message || "No Routes Found"}
              </h3>
            </div>
          </div>
        ) : response?.no_matching_routes_found ? (
          <div className="flex items-start space-x-3 py-6 px-4 bg-orange-50 border border-orange-200 rounded-lg">
            <AlertCircle className="h-5 w-5 text-orange-600 flex-shrink-0 mt-0.5" />
            <div>
              <h3 className="font-semibold text-orange-900">
                No matching routes found for the selected criteria.
              </h3>
            </div>
          </div>
        ) : routesData.length > 0 ? (
          <div className="space-y-6">
            <Tabs value={`route-${selectedTabIndex}`} onValueChange={(val) => {
              setSelectedTabIndex(parseInt(val.split("-")[1]));
            }}>
              <TabsList className="grid w-full" style={{ gridTemplateColumns: `repeat(${Math.min(routesData.length, 5)}, 1fr)` }}>
                {routesData.map((_, index) => (
                  <TabsTrigger key={index} value={`route-${index}`}>
                    Route {index + 1}
                  </TabsTrigger>
                ))}
              </TabsList>

              {routesData.map((route, index) => (
                <TabsContent key={index} value={`route-${index}`}>
                  <Card>
                    <CardHeader>
                      <CardTitle className="text-lg">
                        Route {index + 1} - Day Details
                      </CardTitle>
                    </CardHeader>
                    <CardContent>
                      <div className="overflow-x-auto">
                        <Table>
                          <TableHeader>
                            <TableRow>
                              <TableHead className="w-[80px]">Day</TableHead>
                              <TableHead>Date</TableHead>
                              <TableHead>Source Destination</TableHead>
                              <TableHead>Next Destination</TableHead>
                              <TableHead className="text-center w-[80px]">
                                Via Route
                              </TableHead>
                              <TableHead className="text-center w-[120px]">
                                Direct Visit
                              </TableHead>
                            </TableRow>
                          </TableHeader>
                          <TableBody>
                            {route.map((row, rowIndex) => (
                              <TableRow key={rowIndex}>
                                <TableCell className="font-medium">
                                  Day {row.day}
                                </TableCell>
                                <TableCell>{row.date}</TableCell>
                                <TableCell>{row.source}</TableCell>
                                <TableCell>{row.next}</TableCell>
                                <TableCell className="text-center">
                                  <Button
                                    variant="outline"
                                    size="sm"
                                    onClick={() => {
                                      toast({
                                        title: "Via Route",
                                        description: "Select via route for Day " + row.day,
                                      });
                                    }}
                                  >
                                    <span className="text-lg">⛳</span>
                                  </Button>
                                </TableCell>
                                <TableCell className="text-center">
                                  <input
                                    type="checkbox"
                                    className="h-4 w-4 rounded border-gray-300"
                                    onChange={(e) => {
                                      const updatedRoute = [...route];
                                      updatedRoute[rowIndex].directVisit =
                                        e.target.checked;
                                      const updatedRoutes = [...routesData];
                                      updatedRoutes[index] = updatedRoute;
                                      setRoutesData(updatedRoutes);
                                    }}
                                  />
                                </TableCell>
                              </TableRow>
                            ))}
                          </TableBody>
                        </Table>
                      </div>
                    </CardContent>
                  </Card>
                </TabsContent>
              ))}
            </Tabs>
          </div>
        ) : null}

        <DialogFooter>
          <Button variant="outline" onClick={onClose}>
            Cancel
          </Button>
          <Button
            onClick={handleSelectRoute}
            disabled={loading || routesData.length === 0}
          >
            Select Route {selectedTabIndex + 1}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};
